### ISSUE TITLE
Can't install module

### ISSUE THREAD

**Issue by m4rc0d1** [inwaar/node-red-contrib-dahua-device#1]
I can't install the module neither from NODE-RED console nor using command line. This is the error I get:

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/inwaar/node-dahua-api.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

I don't have git installed on my system, so this can be the problem, but all other modules I've installed didn't create any issue.

**Comment by 0x4d0x44** [comment]
Confirmed: I installed git (Debian 9.8) and the node installed.

It would be nice if the node had no dependencies on git...
