### ISSUE TITLE
Can't install dahua library - error log

### ISSUE THREAD

**Issue by aechile** [inwaar/node-red-contrib-dahua-device#10]
Hi everybody,
I tried to install this this library but I always get the following error log message. I am still very new Node-RED user and maby somebody can help me with this. I have the node red v1.0.5 running on a Victron VenusGX device.

root@beaglebone:~# vi
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--no-audit',
1 verbose cli   '--no-update-notifier',
1 verbose cli   '--save',
1 verbose cli   '--save-prefix="~"',
1 verbose cli   '--production',
1 verbose cli   'node-red-contrib-dahua-device@0.0.2' ]
2 info using npm@6.14.9
3 info using node@v8.15.0
4 verbose npm-session d504c321678dbacf
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/node-red-contrib-dahua-device 2318ms (from cache)
8 silly pacote version manifest for node-red-contrib-dahua-device@0.0.2 fetched in 2657ms
9 timing stage:loadCurrentTree Completed in 3317ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 6ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2688ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule node-red-contrib-dahua-device@0.0.2 checking installable status
17 silly fetchPackageMetaData error for node-dahua-api@github:inwaar/node-dahua-api Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/inwaar/node-dahua-api.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 http fetch GET 304 https://registry.npmjs.org/moment 672ms (from cache)
19 silly pacote range manifest for moment@^2.24.0 fetched in 732ms
20 silly resolveWithNewModule moment@2.29.1 checking installable status
21 timing stage:rollbackFailedOptional Completed in 36ms
22 timing stage:runTopLevelLifecycles Completed in 6961ms
23 silly saveTree node-red-project@0.0.1
23 silly saveTree +-- node-red-contrib-bool-gate@1.0.2
23 silly saveTree +-- node-red-contrib-broadlink-control@2.1.2
23 silly saveTree | +-- events@3.2.0
23 silly saveTree | `-- os@0.1.1
23 silly saveTree +-- node-red-contrib-dahua-device@0.0.2
23 silly saveTree | `-- moment@2.29.1
23 silly saveTree +-- node-red-contrib-frequency-meter@0.0.1
23 silly saveTree +-- node-red-contrib-hysteresis@0.3.0
23 silly saveTree +-- node-red-contrib-interval-length@0.0.4
23 silly saveTree | +-- parse-ms@1.0.1
23 silly saveTree | `-- pretty-ms@3.0.0
23 silly saveTree |   `-- plur@2.1.2
23 silly saveTree |     `-- irregular-plurals@1.4.0

Thanks and kind regards

**Comment by inwaar** [comment]
Hi aechile, install `git` and try again.

**Comment by aechile** [comment]
> Hi aechile, install `git` and try again.
Hi inwaar,
you refer on this package?
[(https://flows.nodered.org/node/node-red-contrib-github-plus)]

Kind regards
